version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: cashapp-proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    image: registry.heroku.com/caashapp/caashapp-service:latest
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: cashapp-server
    ports:
      # 5005 on host since frontend runs on 3000
      - '5005:5005'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
  db:
    container_name: cashapp-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    networks:
      - backend
    ports:
      # NOTE: not default on host!! only b/c conflicts w/ other running postgres
      - '5434:5432'
      
  emailengine:
      restart: always
      image: andris9/emailengine:v2
      ports:
          # API and web interface
          - '3001:3000'
          # SMTP for message submission
          - '2525:2525'
      networks:
        - backend
      depends_on:
          - redis
      environment:
          # Configuration to EmailEngine can be passed via environment variables
          # For full list see https://github.com/postalsys/emailengine#config-mapping

          # Settings to write to v1/settings on startup (https://api.emailengine.app/#operation/postV1Settings)
          # The following value is a YAML block scalar string, so make it sure it is properly indented
          # This configuration enables SMTP server for local submission
          EENGINE_SETTINGS: >
              {
                  "smtpServerEnabled": true,
                  "smtpServerPort": 2525,
                  "smtpServerHost": "0.0.0.0",
                  "smtpServerAuthEnabled": true,
                  "smtpServerPassword": "passw0rd"
              }
          # Encryption secret
          EENGINE_SECRET: 'secret'
          # Database connection URL
          EENGINE_REDIS: 'redis://redis:6379/2'
  
  redis:
      image: redis:alpine
      restart: always
      networks:
        - backend
      volumes:
          - /data

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
